# Square image ResFiT fine-tuning configuration

defaults:
  - /resfit/default

task:
  env_name: Square
  obs_type: image
  image_keys:
    - agentview_image
    - robot0_eye_in_hand_image
  lowdim_keys:
    - robot0_eef_pos
    - robot0_gripper_qpos
  horizon: 16
  obs_steps: 2
  act_steps: 8
  max_episode_steps: 400
  crop_shape: [76, 76]

network:
  image_backbone: vit
  vit_embed_dim: 128
  vit_num_heads: 4
  vit_depth: 1
